version: "3.9"

services:
  database: 
    image: postgres
    container_name: database_luizalabapp
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=userluizalabapp
      - POSTGRES_PASSWORD=Luiz@App
      - POSTGRES_DB=luizalabapp
    volumes:
      - pgdata:/data/postgres


  app:
    build: .
    container_name: luizalabapp
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229 
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database



volumes:
  pgdata:
    driver: local